# Generated by Django 4.2.1 on 2023-05-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('passport', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('experience', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='theater',
            field=models.ManyToManyField(to='lab.theater'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PlayDirector',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lab.employee')),
                ('theater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('main', 'main'), ('sec', 'secondary')], max_length=4)),
                ('performance_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.performance')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.actor')),
            ],
        ),
    ]
